import { readFileSync } from 'node:fs';
const checks: Array<[string,boolean]> = [];
const check=(n:string,v:boolean)=>checks.push([n,v]);
const types=readFileSync('src/types/game.ts','utf8');
const canvas=readFileSync('src/components/GameCanvas.tsx','utf8');
const renderer=readFileSync('src/components/canvas/favelaRenderer.ts','utf8');
check('projectiles carry optional visual class', types.includes("visualStyle?: 'pistol' | 'fuzil' | 'moto' | 'rival'"));
check('ally weapon class feeds muzzle', canvas.includes('addMuzzleFlash(muzzleX, muzzleY, angle, factionConfig.color, weaponSound)'));
check('rival weapon class feeds muzzle', canvas.includes('addMuzzleFlash(muzzleX, muzzleY, combatAngle, r.color, rivalWeaponStyle)'));
check('ally projectile stores class', canvas.includes('visualStyle: weaponSound'));
check('rival projectile stores class', canvas.includes('visualStyle: rivalWeaponStyle'));
check('rifle tracer is longest', renderer.includes("style === 'fuzil' ? 16"));
check('moto tracer is restrained', renderer.includes("style === 'moto' ? 8.5"));
check('damage pulses aggregate spatially', canvas.includes('Math.hypot(ft.x - x, ft.y - y) < 20'));
check('aggregated damage remains bounded', canvas.includes('Math.min(9999, previous + amount)'));
check('dense numeric spam has adaptive suppression', canvas.includes('floatingTextsRef.current.length > 48'));
for(const [n,v] of checks) console.log(`${v?'PASS':'FAIL'} | ${n}`);
if(checks.some(([,v])=>!v)) process.exit(1);
console.log(`COMBAT_VISUALS_11G ${checks.length}/${checks.length} PASS`);
