const endpoint=process.env.CDP_ENDPOINT||'http://127.0.0.1:9236/json';
const stressSpeed=Number(process.env.STRESS_SPEED||5);
const allyCount=Number(process.env.ALLY_COUNT||135);
const rivalCount=Number(process.env.RIVAL_COUNT||32);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const targets=await (await fetch(endpoint)).json();
const target=targets.find(t=>t.type==='page'&&t.url.includes('localhost:3000'));
if(!target) throw new Error('game page missing');
const ws=new WebSocket(target.webSocketDebuggerUrl);
await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});
let seq=0; const pending=new Map();
ws.onmessage=e=>{const m=JSON.parse(e.data);if(!m.id||!pending.has(m.id))return;const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result)};
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))});
await send('Runtime.enable');
const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.text);return r.result.value};
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});
await evaluate(`(()=>{const key='factions_war_pt_br_save_v2';const s=JSON.parse(localStorage.getItem(key));if(!s)throw new Error('save missing');
const allies=Array.from({length:${allyCount}},(_,i)=>({id:'stress-a-'+i,type:i%10===0?'soldado_fuzil':'soldado_base',name:'Stress Ally',x:120+(i%15)*68,y:690-Math.floor(i/15)*42,vx:0,vy:-1,hp:10000,maxHp:10000,speed:1.2,damage:3,attackRange:220,attackCooldown:.45,attackTimer:(i%10)*.03,scavengeCooldown:0,targetId:null,color:'#ef4444',radius:11,variant:i%3}));
const rivals=Array.from({length:${rivalCount}},(_,i)=>({id:'stress-r-'+i,type:i%8===0?'atirador_fuzil':'soldado_pistola',name:'Stress Rival',x:180+(i%8)*125,y:90+Math.floor(i/8)*95,vx:0,vy:.2,hp:10000,maxHp:10000,speed:.9,damage:3,attackRange:210,attackCooldown:.5,attackTimer:(i%8)*.04,targetId:null,state:'patrol',color:'#3b82f6',radius:12,factionTag:'PCC',variant:i%3,patrolTargetX:640,patrolTargetY:360,patrolWaitTimer:0}));
s.gameSpeed=${stressSpeed};s.currentTerritoryId=6;s.runHighestTerritoryReached=6;s.maxAllies=${allyCount};s.intel=100;s.upgrades={};s.autoRecruitFallen=false;s.autoCollectAmmo=false;
s.battleSnapshot={version:1,runId:s.runId,territoryId:6,faction:s.playerFaction,capturedAt:Date.now(),allies,rivals,fallen:[],bullets:[],obstacles:[],spawnElapsedMs:0,autoRecruitElapsedMs:0};localStorage.setItem(key,JSON.stringify(s));location.reload();return true})()`);
await sleep(1400);
const measureExpr=`new Promise(resolve=>{let frames=0;const start=performance.now();const tick=t=>{frames++;if(t-start>=2500)resolve({frames,ms:t-start,fps:frames*1000/(t-start)});else requestAnimationFrame(tick)};requestAnimationFrame(tick)})`;
const baseline=await evaluate(measureExpr);
const rect=await evaluate(`(()=>{const r=document.querySelector('canvas').getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height}})()`);
const movingMeasure=send('Runtime.evaluate',{expression:measureExpr,returnByValue:true,awaitPromise:true});
for(let i=0;i<120;i++){
  const x=rect.x+40+(i%20)*Math.max(8,(rect.w-80)/20);
  const y=rect.y+60+((i*7)%12)*Math.max(8,(Math.min(rect.h,520)-120)/12);
  await send('Input.dispatchMouseEvent',{type:'mouseMoved',x,y});
  await sleep(10);
}
const movingResult=await movingMeasure;
const moving=movingResult.result.value;
const text=await evaluate('document.body.innerText');
const perf=await evaluate('window.__GAME_PERF__ || null');
const savedCounts=await evaluate(`(()=>{const s=JSON.parse(localStorage.getItem('factions_war_pt_br_save_v2')||'null');return{allies:s?.battleSnapshot?.allies?.length||0,rivals:s?.battleSnapshot?.rivals?.length||0,bullets:s?.battleSnapshot?.bullets?.length||0,fallen:s?.battleSnapshot?.fallen?.length||0}})()`);
console.log(`STRESS_04B baseline_fps=${baseline.fps.toFixed(1)} mousemove_fps=${moving.fps.toFixed(1)} units=${allyCount+rivalCount} speed=${stressSpeed}x bullets=${savedCounts.bullets} fallen=${savedCounts.fallen}`);
console.log('STRESS_04C profiler='+JSON.stringify(perf));
console.log(`STRESS_04B status=${baseline.fps>=30&&moving.fps>=30&&text.includes('Guerra de Fac')?'PASS':'FAIL'}`);
await send('Emulation.clearDeviceMetricsOverride');
ws.close();
if(baseline.fps<30||moving.fps<30) process.exitCode=1;
